### ISSUE TITLE
[Bug]: creating a new page in the new headless mode times out

### ISSUE THREAD

**Issue by morkai** [puppeteer/puppeteer#11066]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () =>
{
  const browser = await puppeteer.launch({
    headless: 'new',
    protocolTimeout: 10000,
    args: ['--no-sandbox']
  });
  
  const pages = await browser.pages();
  console.log(`${pages.length} pages before closing`);
  for (const page of pages)
  {
    console.log('close', page.url());
    await page.close();
  }
  console.log(`${(await browser.pages()).length} pages after closing`);

  await wait(100);
  await goToPage(browser, 'pl');
  await goToPage(browser, 'de');
  await goToPage(browser, 'ch');
  
  await browser.close();
})();

async function goToPage(browser, l)
{
  console.log(l, 'newPage');
  const page = await browser.newPage();
  console.log(l, 'goto');
  await page.goto(`https://google.${l}`);
  console.log(l, 'close');
  await page.close();
}

function wait(ms)
{
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

### Error string

Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

After updating `puppeteer` to the latest version I wanted to check the (soon to be the default) new headless mode. I'm using `puppeteer` with a custom [`lightning-pool`](https://github.com/panates/lightning-pool) which automatically closes all browser pages after the browser resource is no longer needed. This results in closing of the automatically opened `about:blank` page (see [#8216](https://github.com/puppeteer/puppeteer/issues/8216)). The next time that browser instance is reused, a call to the `browser.newPage()` function fails.

The old headless mode has no such issue.

### Expectation

Calling `browser.newPage()` when `browser.pages().length === 0` should result in the creation of a new page in the `new` headless mode.

Expected output of running the example:

```
1 pages before closing
close about:blank
0 pages after closing
pl newPage
pl goto
pl close
de newPage
de goto
de close
ch newPage
ch goto
ch close
```

### Reality

If some time passes between closing the only existing page and opening a new one, the first call to the `browser.newPage()` throws:

> ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

If the new page is opened immediately (remove the call to `wait(100)`) the error changes to:

> ProtocolError: Protocol error (Target.createTarget): Failed to open a new tab

Actual output of running the example:

```
1 pages before closing
close about:blank
0 pages after closing
pl newPage
file:///.../node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:39
    #error = new ProtocolError();
             ^

ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
```

It looks like closing the last page in the new headless mode also closes all browser processes.

### Puppeteer version

21.3.6

### Node version

20.8.0

### Package manager

npm

### Package manager version

8.13.2

### Operating system

Windows

**Comment by OrKoN** [comment]
Do you have browser logs when this happens? (dumpio: true to the launch flag).

I am unable to reproduce locally so far.

**Comment by morkai** [comment]
```TypeScript
import puppeteer from 'puppeteer';
(async () => {
  const browser = await puppeteer.launch({
    headless: 'new',
    protocolTimeout: 10000,
    args: ['--no-sandbox'],
    dumpio: true
  });
  for (const page of (await browser.pages()))
    await page.close(); 
  await goToPage(browser, 'pl');
  await goToPage(browser, 'de');
  await goToPage(browser, 'ch');
  await browser.close();
})();
async function goToPage(browser, l) {
  console.log(l, 'newPage');
  const page = await browser.newPage();
  await page.goto(`https://google.${l}`);
  await page.close();
}
```

Output:
```
F:\Workspace\test>node test.mjs
[2460:22032:1004/155829.317:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.

DevTools listening on ws://127.0.0.1:33356/devtools/browser/5fe71cf2-c83d-4dbd-b54a-083a6237ac30
pl newPage
file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:39
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (Target.createTarget): Failed to open a new tab
    at <instance_members_initializer> (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:39:14)
    at new Callback (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:43:16)
    at CallbackRegistry.create (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:82:26)
    at Connection._rawSend (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:203:26)
    at Connection.send (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:197:21)
    at CdpBrowser._createPageInContext (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:186:53)
    at CdpBrowserContext.newPage (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:308:30)
    at CdpBrowser.newPage (file:///F:/Workspace/test/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:183:43)
    at goToPage (file:///F:/Workspace/test/test.mjs:18:30)
    at file:///F:/Workspace/test/test.mjs:11:9

Node.js v20.8.0
```

With `headless: true` I can see that after `launch()` there are 4-5 chrome.exe processes. After the first `page.close()` there is one less process and then three times one more and one less.

With `headless: 'new'` there are 7 processes after `launch()` and none after the first `page.close()`.

See https://youtu.be/ZmGWHyxuyCs

**Comment by OrKoN** [comment]
Filed upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1489271 (seems to be a windows-only behaviour)

**Comment by Chetanp23** [comment]
@OrKoN
It seems like issue resolved by chromium team member. 
Is it fixed ?

**Comment by OrKoN** [comment]
@Chetanp23 it will be first release with with m120 https://chromiumdash.appspot.com/commit/991b1ba114e1d6fa3dfb903f0e3f1177d99837b9

**Comment by Chetanp23** [comment]
@freekmurze take a look at this comment 
https://github.com/puppeteer/puppeteer/issues/11066#issuecomment-1825712224

**Comment by Lightning00Blade** [comment]
Puppeteer v21.9.0 downloads M121, so this should be resolve, leave open if issue is still reproducible.

**Comment by Prapul1614** [comment]
How did u overcame this error - "ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed."
