### ISSUE TITLE
[Bug]: Failed to open many pages with the '--incognito' property

### ISSUE THREAD

**Issue by dylanzhou427** [puppeteer/puppeteer#12005]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false, // 是否为无头模式，这里设置为false便于观察
    args: ['--incognito'], // 启用无痕模式
  });

  const page = await browser.newPage();
  await page.goto('https://www.google.com/');

  // ... 其他操作

  // await browser.close(); // 最后记得关闭浏览器实例
})();
```

### Error string

Two browser Windows open

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I am looking to open multiple pages in an incognito browser window. However, after using the `puppeteer.launch({args: ['--incognito']})` method to launch an incognito browser, when I create a new page with `browser.newPage()` and subsequently execute the `goto` method to navigate to the target URL, the outcome is that two separate browser windows are opened - one incognito and one non-incognito - with the target URL being loaded in the non-incognito browser. The actual effect and a screenshot of the code are presented below.
<img width="1194" alt="image" src="https://github.com/puppeteer/puppeteer/assets/144797635/7c92123b-7e94-4bf4-9d57-1f1011ced357">
<img width="557" alt="image" src="https://github.com/puppeteer/puppeteer/assets/144797635/5721d262-64aa-4efc-9aa9-68a290ae0f74">

### Expectation

Expect the target URL to open as a TAB in the incognito browser each time the goto method is executed, inheriting the browser's incognito mode.

### Reality

As mentioned above

### Puppeteer version

v22.0.0

### Node version

v20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by dylanzhou427** [comment]
It has been determined to run locally, and the above screenshot is local operation, independent of other dependencies

**Comment by OrKoN** [comment]
Appears to be an issue in Chrome. I'd suggest using https://pptr.dev/api/puppeteer.browser.createbrowsercontext/ instead of relying on flags.

**Comment by dylanzhou427** [comment]
Alright, thank you. The issue has been resolved using your solution.

**Comment by lanly-dev** [comment]
how do you create new page/tab in incognito mode? I can't seem to make it work from using `browser.createbrowsercontext()`.
Is the an example code that I could try on?

**Comment by OrKoN** [comment]
there is an example in the link posted above https://pptr.dev/api/puppeteer.browser.createbrowsercontext#example

**Comment by lanly-dev** [comment]
> there is an example in the link posted above https://pptr.dev/api/puppeteer.browser.createbrowsercontext#example

Still can't get the incognito mode working. I modified some changes to the example code in order to run it, like this:
```
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch({ headless: false })
  const context = await browser.createBrowserContext()
  const page = await context.newPage()
  await page.goto('https://example.com')
})()
```
"puppeteer": "^22.7.1"

**Comment by seanmamasde** [comment]
yeah still doesn't work, I am on `puppeteer": "^22.12.1`. After creating the only context using `const browser = await puppeteer.launch({ args: ["--incognito"] });` and then creating a new page afterwards it's still broken. Seems like the `newPage()` will only create a non-incognito window. The temporary solution I am using right now is after creating a browser with an only incognito tab, use the `pages()[0]` to get the only page then use `goto()` on that page, but this only gives a single tab.
