### ISSUE TITLE
Unexpected change in `⁠proxyServer`

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#13599]
When a browser is created by puppeteeer, it will accept `proxyServer` as optional string value:

```js
const browser = await puppeteer.launch()
const context = await browser.createBrowserContext({ proxyServer: 'https://myproxy.com' })
const page = await context.newPage()
await page.goto(targetUrl)
```

I recently noted this is not working in this way anymore: The `proxyServer` must be a host, not an URL.

This is the correct way to pass `proxyServer`:

```js
const browser = await puppeteer.launch()
const context = await browser.createBrowserContext({ proxyServer: new URL(proxyUrl).host })
const page = await context.newPage()
await page.goto(targetUrl)
```

I noted this subtle change when uprading from `23.11.1` to `24.2.0` ([related browserless PR](https://github.com/microlinkhq/browserless/pull/602))

I believe this change was not planned at puppeteer core level, however it's a change that can break things.

As mininum, this behavior should be documented, but ideally I think puppeteer can be proxy integration more affordable and simply get host from the URL or throw an error if the format is not the expected.

Also, related to make proxy more affordable, could be nice to take ride of https://github.com/puppeteer/puppeteer/issues/7608

**Comment by OrKoN** [comment]
I do not see any changes related to the proxy server option in https://github.com/puppeteer/puppeteer/compare/puppeteer-v23.11.1...puppeteer-v24.2.0 Do you have a more specific range when the behavior changed for you?

Could you please provide the proxy server implementation that you are using?

**Comment by OrKoN** [comment]
Our tests pass with a full URL as previously https://github.com/puppeteer/puppeteer/blob/main/test/src/proxy.spec.ts#L186

**Comment by Kikobeats** [comment]
Thanks for clarifying; I wrote a more complete example based in the test, and I'm not seeing proxy server being called:

```
'use strict'

import { request, createServer as nodeCreateServer } from 'http'
import puppeteer from 'puppeteer'

let port = 1337

const endpoint = server => {
  const { address, port, family } = server.address()
  const hostname = family === 'IPv6' ? `[${address}]` : address
  return new URL(`http://${hostname}:${port}`).toString()
}

const createServer = async handler => {
  const server = nodeCreateServer(handler)

  server.url = await (async () => {
    const { promise, resolve } = Promise.withResolvers()
    server.listen({ host: '127.0.0.1', port: port++ }, () => resolve(endpoint(server)))
    return promise
  })()

  const close = server.close.bind(server)

  server.close = () => new Promise(resolve => close(resolve))

  return server
}

const server = await createServer((_, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' })
  res.end('<html><body><h1>This is server 1</h1></body></html>')
})

const proxiedRequestUrls = []

const proxy =
  await createServer((originalRequest, originalResponse) => {
    proxiedRequestUrls.push(originalRequest.url)

    const proxyRequest = request(
      originalRequest.url,
      {
        method: originalRequest.method,
        headers: originalRequest.headers
      },
      proxyResponse => {
        originalResponse.writeHead(
          proxyResponse.statusCode,
          proxyResponse.headers
        )
        proxyResponse.pipe(originalResponse, { end: true })
      }
    )

    originalRequest.pipe(proxyRequest, { end: true })
  })

console.log()
console.log(' Proxy URL:', proxy.url)
console.log('Server URL:', server.url)
console.log()

const browser = await puppeteer.launch()
const context = await browser.createBrowserContext({ proxyServer: proxy.url })
const page = await context.newPage()
await page.goto(server.url)

const content = await page.content()
console.log(content)
console.log({ proxiedRequestUrls })

await page.screenshot({ path: 'screenshot.png' })

await browser.close()
await proxy.close()
await server.close()
await proxy.close()
```

The output for me is:

```
 Proxy URL: http://127.0.0.1:1338/
Server URL: http://127.0.0.1:1337/

<html><head></head><body><h1>This is server 1</h1></body></html>
{ proxiedRequestUrls: [] }
```

Can you help me to understand what's happening?

**Comment by OrKoN** [comment]
I have not debugged that code yet but it also does not work with puppeteer@23.11.1:

```
❯ node proxy.mjs

Proxy URL: http://127.0.0.1:10874/
Server URL: http://127.0.0.1:10873/
executable path undefined

<html><head></head><body><h1>This is server 1</h1></body></html>
{ proxiedRequestUrls: [] }
file:///Users/alexrudenko/src/pptr-test/proxy.mjs:82
  throw new Error('not proxied')
        ^

Error: not proxied
    at file:///Users/alexrudenko/src/pptr-test/proxy.mjs:82:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

does it pass for you with 23.11.1? which OS is it?

**Comment by OrKoN** [comment]
The difference to our test is that our tests picks a non-localhost hostname like 192.0.0.2 as I think Chrome never proxied local requests (https://github.com/puppeteer/puppeteer/blob/main/test/src/proxy.spec.ts#L34). Starting the proxy on `192.0.0.2` (the IP I have in the local network) makes the script work for me (with the latest Chrome + Puppeteer as well).

**Comment by Kikobeats** [comment]
@OrKoN got it although I didn't get it to work as expected.

EvenI use `os.hostname()` instead of 127.0.0.1 or a cloudflare tunnel it's failing in the same way ☹️

**Comment by OrKoN** [comment]
here is a working version:

```
import { request, createServer as nodeCreateServer } from 'http'
import os from 'os'
import puppeteer from 'puppeteer'

let port = 11337

let HOSTNAME = os.hostname();

// Hostname might not be always accessible in environments other than GitHub
// Actions. Therefore, we try to find an external IPv4 address to be used as a
// hostname in these tests.
const networkInterfaces = os.networkInterfaces();
for (const key of Object.keys(networkInterfaces)) {
  const interfaces = networkInterfaces[key];
  for (const net of interfaces || []) {
    if (net.family === 'IPv4' && !net.internal) {
      HOSTNAME = net.address;
      break;
    }
  }
}

console.log('HOSTNAME', HOSTNAME)

const endpoint = server => {
  const { port } = server.address()
  return `http://${HOSTNAME}:${port}`;
}

const createServer = async handler => {
  const server = nodeCreateServer(handler)

  server.url = await (async () => {
    const { promise, resolve } = Promise.withResolvers()
    server.listen({ host: '0.0.0.0', port: port++ }, () => resolve(endpoint(server)))
    return promise
  })()

  const close = server.close.bind(server)

  server.close = () => new Promise(resolve => close(resolve))

  return server
}

const server = await createServer((_, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' })
  res.end('<html><body><h1>This is server 1</h1></body></html>')
})

const proxiedRequestUrls = []

const proxy =
  await createServer((originalRequest, originalResponse) => {
    proxiedRequestUrls.push(originalRequest.url)

    const proxyRequest = request(
      originalRequest.url,
      {
        method: originalRequest.method,
        headers: originalRequest.headers
      },
      proxyResponse => {
        originalResponse.writeHead(
          proxyResponse.statusCode,
          proxyResponse.headers
        )
        proxyResponse.pipe(originalResponse, { end: true })
      }
    )

    originalRequest.pipe(proxyRequest, { end: true })
  })

console.log()
console.log(' Proxy URL:', proxy.url)
console.log('Server URL:', server.url)
console.log()

const browser = await puppeteer.launch()
const context = await browser.createBrowserContext({ proxyServer: proxy.url })
const page = await context.newPage()
await page.goto(server.url)

const content = await page.content()
console.log(content)
console.log({ proxiedRequestUrls })

await page.screenshot({ path: 'screenshot.png' })

await browser.close()
await proxy.close()
await server.close()
await proxy.close()
```

**Comment by Kikobeats** [comment]
@OrKoN although my main concern was resolved, I'm trying to write a e2e test to verify this, essentially deploying the proxy logic in a remote server.

As much as I tried, the brower can't the URL when the remote proxy is provided.

![Image](https://github.com/user-attachments/assets/f92adf0d-8641-40a3-89f4-db65e4c54800)

This is the only change in your example:

```js
const context = await browser.createBrowserContext({ proxyServer: 'https://http-proxy-morning-snowflake-1128.fly.dev' })
```

If I verify the proxy using cURL, it works:

```
curl -i -x https://http-proxy-morning-snowflake-1128.fly.dev http://example.com
```

Do you have any idea why? I will keep the remote proxy running in case you can to test it.

**Comment by OrKoN** [comment]
Does the curl work if it is https://example.com?

**Comment by OrKoN** [comment]
```
❯ curl -i -x https://http-proxy-morning-snowflake-1128.fly.dev https://example.com
HTTP/1.1 502 Bad Gateway
server: Fly/12401d8b4 (2025-02-12)
via: 1.1 fly.io
fly-request-id: 01JKZ1Y8NXT868ME1CYB5V3SSG-arn
content-length: 0
date: Thu, 13 Feb 2025 07:04:01 GMT

curl: (56) CONNECT tunnel failed, response 502
```

**Comment by Kikobeats** [comment]
@OrKoN, sorry the machine auto-stopped during the night. It's back up now; can you test it? 🙏

**Comment by OrKoN** [comment]
Still the same but I do get the response for http:// like before.

**Comment by Kikobeats** [comment]
@OrKoN, that's probably the issue. Chromium is forcing HTTPS, and the proxy can't handle it. Let me handle it on my side for now 🙂

**Comment by OrKoN** [comment]
You can turn off the auto-upgrades (there are multiple feature flags for now while the feature is being rolled out to users, IIRC one is --disable-features=HttpsUpgrades). Also, the headless shell would not have the auto-upgrades behavior (since it is not shipping for regular users).
